/*
 * gst-webview-html.h - Embedded HTML/CSS/JS for webview module
 *
 * Copyright (C) 2026 Zach Podbielniak
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Single-page application rendered in the browser. Connects via
 * WebSocket for live terminal streaming. Supports read-only and
 * read-write modes with optional token/password authentication.
 */

#ifndef GST_WEBVIEW_HTML_H
#define GST_WEBVIEW_HTML_H

static const gchar GST_WEBVIEW_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>GST Terminal</title>\n"
"<style>\n"
"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"html, body { width: 100%; height: 100%; overflow: hidden; }\n"
"body {\n"
"  background: #000;\n"
"  color: #d3d7cf;\n"
"  font-family: 'Liberation Mono', 'DejaVu Sans Mono', 'Courier New', monospace;\n"
"  font-size: 14px;\n"
"  line-height: 1;\n"
"}\n"
"\n"
"/* Auth dialog */\n"
"#auth-overlay {\n"
"  display: none;\n"
"  position: fixed; top: 0; left: 0; width: 100%; height: 100%;\n"
"  background: rgba(0,0,0,0.85);\n"
"  z-index: 100;\n"
"  justify-content: center; align-items: center;\n"
"}\n"
"#auth-overlay.active { display: flex; }\n"
"#auth-dialog {\n"
"  background: #1e1e2e; border: 1px solid #45475a; border-radius: 8px;\n"
"  padding: 24px; min-width: 320px; color: #cdd6f4;\n"
"}\n"
"#auth-dialog h2 { margin-bottom: 16px; font-size: 16px; color: #cba6f7; }\n"
"#auth-dialog input {\n"
"  width: 100%; padding: 8px 12px; margin-bottom: 12px;\n"
"  background: #313244; border: 1px solid #45475a; border-radius: 4px;\n"
"  color: #cdd6f4; font-family: inherit; font-size: 14px;\n"
"  outline: none;\n"
"}\n"
"#auth-dialog input:focus { border-color: #cba6f7; }\n"
"#auth-dialog button {\n"
"  width: 100%; padding: 8px; background: #cba6f7; color: #1e1e2e;\n"
"  border: none; border-radius: 4px; font-size: 14px; cursor: pointer;\n"
"  font-weight: bold;\n"
"}\n"
"#auth-dialog button:hover { background: #b4befe; }\n"
"#auth-error {\n"
"  color: #f38ba8; font-size: 12px; margin-bottom: 8px; display: none;\n"
"}\n"
"\n"
"/* Terminal display */\n"
"#terminal {\n"
"  white-space: pre;\n"
"  padding: 4px;\n"
"  position: relative;\n"
"}\n"
".row { height: 1em; }\n"
"\n"
"/* Cursor blink animation */\n"
"@keyframes cursor-blink {\n"
"  0%, 49% { visibility: visible; }\n"
"  50%, 100% { visibility: hidden; }\n"
"}\n"
"\n"
"/* Cursor styles */\n"
".cursor-block {\n"
"  background: #d3d7cf;\n"
"  color: #000000;\n"
"}\n"
".cursor-bar {\n"
"  border-left: 2px solid #d3d7cf;\n"
"}\n"
".cursor-underline {\n"
"  border-bottom: 2px solid #d3d7cf;\n"
"}\n"
".cursor-blink {\n"
"  animation: cursor-blink 1s step-end infinite;\n"
"}\n"
"\n"
"/* Status bar */\n"
"#status-bar {\n"
"  position: fixed; bottom: 0; right: 0;\n"
"  padding: 2px 8px;\n"
"  font-size: 11px;\n"
"  background: rgba(30,30,46,0.9);\n"
"  color: #6c7086;\n"
"  border-top-left-radius: 4px;\n"
"  z-index: 50;\n"
"}\n"
"#status-bar .connected { color: #a6e3a1; }\n"
"#status-bar .disconnected { color: #f38ba8; }\n"
"#status-bar .mode-rw { color: #fab387; }\n"
"#status-bar .mode-ro { color: #6c7086; }\n"
"#status-bar .scroll-info { color: #f9e2af; }\n"
"\n"
"/* Bell flash */\n"
"@keyframes bell-flash {\n"
"  0% { outline: 2px solid #f9e2af; }\n"
"  100% { outline: 2px solid transparent; }\n"
"}\n"
"#terminal.bell { animation: bell-flash 0.15s ease-out; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<div id=\"auth-overlay\">\n"
"  <div id=\"auth-dialog\">\n"
"    <h2>GST Terminal - Authentication</h2>\n"
"    <div id=\"auth-error\">Authentication failed. Please try again.</div>\n"
"    <input type=\"password\" id=\"auth-input\" placeholder=\"Enter token or password\" autocomplete=\"off\">\n"
"    <button id=\"auth-submit\">Connect</button>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div id=\"terminal\"></div>\n"
"\n"
"<div id=\"status-bar\">\n"
"  <span id=\"status-conn\" class=\"disconnected\">disconnected</span>\n"
"  <span id=\"status-mode\"></span>\n"
"  <span id=\"status-scroll\"></span>\n"
"</div>\n"
"\n"
"<script>\n"
"(function() {\n"
"'use strict';\n"
"\n"
"/* --- State --- */\n"
"var cols = 80, rows = 24;\n"
"var screen = [];    /* 2D: screen[row] = [{c,fg,bg,a,w}, ...] */\n"
"var cursor = {x: 0, y: 0, shape: 'block', visible: true};\n"
"var prevCursor = {x: -1, y: -1};\n"
"var readOnly = true;\n"
"var scrollOffset = 0;\n"
"var scrollCount = 0;\n"
"var ws = null;\n"
"var reconnectDelay = 1000;\n"
"var maxReconnectDelay = 30000;\n"
"var authCredential = '';\n"
"var authRequired = false;\n"
"\n"
"/* --- DOM refs --- */\n"
"var termEl = document.getElementById('terminal');\n"
"var statusConn = document.getElementById('status-conn');\n"
"var statusMode = document.getElementById('status-mode');\n"
"var authOverlay = document.getElementById('auth-overlay');\n"
"var authInput = document.getElementById('auth-input');\n"
"var authSubmit = document.getElementById('auth-submit');\n"
"var authError = document.getElementById('auth-error');\n"
"var statusScroll = document.getElementById('status-scroll');\n"
"\n"
"/* --- Auth handling --- */\n"
"function checkAuthNeeded() {\n"
"  /* Try connecting; if auth fails, show dialog */\n"
"  connect();\n"
"}\n"
"\n"
"function showAuthDialog() {\n"
"  authRequired = true;\n"
"  authOverlay.classList.add('active');\n"
"  authInput.value = '';\n"
"  authInput.focus();\n"
"}\n"
"\n"
"function hideAuthDialog() {\n"
"  authOverlay.classList.remove('active');\n"
"  authError.style.display = 'none';\n"
"}\n"
"\n"
"authSubmit.addEventListener('click', function() {\n"
"  authCredential = authInput.value;\n"
"  hideAuthDialog();\n"
"  connect();\n"
"});\n"
"\n"
"authInput.addEventListener('keydown', function(e) {\n"
"  if (e.key === 'Enter') {\n"
"    authCredential = authInput.value;\n"
"    hideAuthDialog();\n"
"    connect();\n"
"  }\n"
"});\n"
"\n"
"/* --- WebSocket connection --- */\n"
"function getUrlParam(name) {\n"
"  var params = new URLSearchParams(location.search);\n"
"  return params.get(name) || '';\n"
"}\n"
"\n"
"function buildWsUrl() {\n"
"  var proto = (location.protocol === 'https:') ? 'wss:' : 'ws:';\n"
"  var url = proto + '//' + location.host + '/ws';\n"
"  /* Inherit token from page URL query param, or use auth dialog credential */\n"
"  var tok = authCredential || getUrlParam('token');\n"
"  var pass = getUrlParam('password');\n"
"  if (tok) {\n"
"    url += '?token=' + encodeURIComponent(tok);\n"
"  } else if (pass) {\n"
"    url += '?password=' + encodeURIComponent(pass);\n"
"  }\n"
"  return url;\n"
"}\n"
"\n"
"function connect() {\n"
"  if (ws && (ws.readyState === WebSocket.CONNECTING || ws.readyState === WebSocket.OPEN)) {\n"
"    return;\n"
"  }\n"
"\n"
"  statusConn.textContent = 'connecting...';\n"
"  statusConn.className = 'disconnected';\n"
"\n"
"  try {\n"
"    ws = new WebSocket(buildWsUrl());\n"
"  } catch(e) {\n"
"    scheduleReconnect();\n"
"    return;\n"
"  }\n"
"\n"
"  ws.onopen = function() {\n"
"    statusConn.textContent = 'connected';\n"
"    statusConn.className = 'connected';\n"
"    reconnectDelay = 1000;\n"
"    authRequired = false;\n"
"  };\n"
"\n"
"  ws.onclose = function(ev) {\n"
"    statusConn.textContent = 'disconnected';\n"
"    statusConn.className = 'disconnected';\n"
"    ws = null;\n"
"\n"
"    /* Code 1008 = policy violation (auth failure) */\n"
"    if (ev.code === 1008) {\n"
"      authError.style.display = 'block';\n"
"      showAuthDialog();\n"
"      return;\n"
"    }\n"
"\n"
"    scheduleReconnect();\n"
"  };\n"
"\n"
"  ws.onerror = function() {\n"
"    /* onclose will fire after this */\n"
"  };\n"
"\n"
"  ws.onmessage = function(ev) {\n"
"    var msg;\n"
"    try { msg = JSON.parse(ev.data); } catch(e) { return; }\n"
"    handleMessage(msg);\n"
"  };\n"
"}\n"
"\n"
"function scheduleReconnect() {\n"
"  if (authRequired) return;\n"
"  setTimeout(function() {\n"
"    connect();\n"
"  }, reconnectDelay);\n"
"  reconnectDelay = Math.min(reconnectDelay * 2, maxReconnectDelay);\n"
"}\n"
"\n"
"/* --- Message handling --- */\n"
"function handleMessage(msg) {\n"
"  switch (msg.type) {\n"
"  case 'full':\n"
"    cols = msg.cols;\n"
"    rows = msg.rows;\n"
"    screen = msg.lines;\n"
"    prevCursor = {x: cursor.x, y: cursor.y};\n"
"    cursor = msg.cursor;\n"
"    if (typeof msg.read_only !== 'undefined') {\n"
"      readOnly = msg.read_only;\n"
"      updateModeDisplay();\n"
"    }\n"
"    updateScrollState(msg);\n"
"    if (msg.title) document.title = msg.title + ' - GST';\n"
"    renderFull();\n"
"    break;\n"
"\n"
"  case 'diff':\n"
"    prevCursor = {x: cursor.x, y: cursor.y};\n"
"    cursor = msg.cursor;\n"
"    updateScrollState(msg);\n"
"    if (msg.rows) {\n"
"      var keys = Object.keys(msg.rows);\n"
"      for (var i = 0; i < keys.length; i++) {\n"
"        var rowIdx = parseInt(keys[i], 10);\n"
"        screen[rowIdx] = msg.rows[keys[i]];\n"
"      }\n"
"      renderDiff(msg.rows);\n"
"    } else {\n"
"      renderCursor();\n"
"    }\n"
"    break;\n"
"\n"
"  case 'resize':\n"
"    cols = msg.cols;\n"
"    rows = msg.rows;\n"
"    /* full update follows */\n"
"    break;\n"
"\n"
"  case 'bell':\n"
"    termEl.classList.remove('bell');\n"
"    void termEl.offsetWidth; /* reflow to restart animation */\n"
"    termEl.classList.add('bell');\n"
"    break;\n"
"\n"
"  case 'title':\n"
"    if (msg.title) document.title = msg.title + ' - GST';\n"
"    break;\n"
"  }\n"
"}\n"
"\n"
"/* --- Rendering --- */\n"
"\n"
"/*\n"
" * renderRow: build HTML for a single row of cells.\n"
" * Coalesces adjacent cells with the same fg/bg/attrs into spans.\n"
" */\n"
"function renderRow(cells, rowIdx) {\n"
"  if (!cells || cells.length === 0) return '';\n"
"  var html = '';\n"
"  var i = 0;\n"
"  var len = cells.length;\n"
"\n"
"  while (i < len) {\n"
"    var cell = cells[i];\n"
"    var fg = cell.fg;\n"
"    var bg = cell.bg;\n"
"    var a = cell.a || 0;\n"
"    var isCursor = (cursor.visible && rowIdx === cursor.y && i === cursor.x);\n"
"    var runCols = cell.w ? 2 : 1; /* column width of first char */\n"
"\n"
"    /* Coalesce run of same style (unless cursor is in this run) */\n"
"    var run = cell.c || ' ';\n"
"    var j = i + 1;\n"
"    if (cell.w) j = i + 1; /* wide char, don't coalesce */\n"
"    if (!isCursor) {\n"
"      while (j < len && cells[j].fg === fg && cells[j].bg === bg &&\n"
"             (cells[j].a || 0) === a && !cells[j].w &&\n"
"             !(cursor.visible && rowIdx === cursor.y && j === cursor.x)) {\n"
"        run += cells[j].c || ' ';\n"
"        runCols++;\n"
"        j++;\n"
"      }\n"
"    }\n"
"\n"
"    /* Build style string with fixed column width */\n"
"    var style = 'display:inline-block;width:' + runCols + 'ch;overflow:hidden';\n"
"    style += ';color:' + fg + ';background:' + bg;\n"
"    var cls = '';\n"
"\n"
"    if (a & 1) style += ';font-weight:bold';\n"
"    if (a & 2) style += ';opacity:0.5';\n"
"    if (a & 4) style += ';font-style:italic';\n"
"    if (a & 8) style += ';text-decoration:underline';\n"
"    if (a & 16) style += ';text-decoration:line-through';\n"
"    if (a & 32) { /* reverse - swap fg/bg */\n"
"      style = 'display:inline-block;width:' + runCols + 'ch;overflow:hidden';\n"
"      style += ';color:' + bg + ';background:' + fg;\n"
"    }\n"
"\n"
"    if (isCursor) {\n"
"      cls = 'cursor-' + cursor.shape + ' cursor-blink';\n"
"    }\n"
"\n"
"    html += '<span style=\"' + style + '\"';\n"
"    if (cls) html += ' class=\"' + cls.trim() + '\"';\n"
"    html += '>';\n"
"    html += escapeHtml(run);\n"
"    html += '</span>';\n"
"\n"
"    i = j;\n"
"  }\n"
"\n"
"  return html;\n"
"}\n"
"\n"
"function renderFull() {\n"
"  var html = '';\n"
"  for (var y = 0; y < rows && y < screen.length; y++) {\n"
"    html += '<div class=\"row\" id=\"r' + y + '\">' + renderRow(screen[y], y) + '</div>';\n"
"  }\n"
"  /* Pad remaining rows if screen is smaller */\n"
"  for (var y2 = screen.length; y2 < rows; y2++) {\n"
"    html += '<div class=\"row\" id=\"r' + y2 + '\"></div>';\n"
"  }\n"
"  termEl.innerHTML = html;\n"
"}\n"
"\n"
"function renderDiff(changedRows) {\n"
"  var keys = Object.keys(changedRows);\n"
"  for (var i = 0; i < keys.length; i++) {\n"
"    var rowIdx = parseInt(keys[i], 10);\n"
"    var el = document.getElementById('r' + rowIdx);\n"
"    if (el) {\n"
"      el.innerHTML = renderRow(changedRows[keys[i]], rowIdx);\n"
"    }\n"
"  }\n"
"\n"
"  /* Re-render old cursor row to remove stale cursor */\n"
"  if (prevCursor.y >= 0 && prevCursor.y !== cursor.y &&\n"
"      !changedRows.hasOwnProperty('' + prevCursor.y)) {\n"
"    var oldEl = document.getElementById('r' + prevCursor.y);\n"
"    if (oldEl && screen[prevCursor.y]) {\n"
"      oldEl.innerHTML = renderRow(screen[prevCursor.y], prevCursor.y);\n"
"    }\n"
"  }\n"
"\n"
"  /* Re-render new cursor row if not already in changedRows */\n"
"  if (cursor.visible && !changedRows.hasOwnProperty('' + cursor.y)) {\n"
"    var cursorEl = document.getElementById('r' + cursor.y);\n"
"    if (cursorEl && screen[cursor.y]) {\n"
"      cursorEl.innerHTML = renderRow(screen[cursor.y], cursor.y);\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"function renderCursor() {\n"
"  /* Re-render old cursor row to clear stale cursor */\n"
"  if (prevCursor.y >= 0 && prevCursor.y !== cursor.y) {\n"
"    var oldEl = document.getElementById('r' + prevCursor.y);\n"
"    if (oldEl && screen[prevCursor.y]) {\n"
"      oldEl.innerHTML = renderRow(screen[prevCursor.y], prevCursor.y);\n"
"    }\n"
"  }\n"
"  /* Re-render new cursor row */\n"
"  if (!cursor.visible) return;\n"
"  var el = document.getElementById('r' + cursor.y);\n"
"  if (el && screen[cursor.y]) {\n"
"    el.innerHTML = renderRow(screen[cursor.y], cursor.y);\n"
"  }\n"
"}\n"
"\n"
"function escapeHtml(str) {\n"
"  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');\n"
"}\n"
"\n"
"function updateModeDisplay() {\n"
"  if (readOnly) {\n"
"    statusMode.innerHTML = ' | <span class=\"mode-ro\">read-only</span>';\n"
"  } else {\n"
"    statusMode.innerHTML = ' | <span class=\"mode-rw\">read-write</span>';\n"
"  }\n"
"}\n"
"\n"
"/* --- Scroll state --- */\n"
"function updateScrollState(msg) {\n"
"  if (typeof msg.scroll_offset !== 'undefined') {\n"
"    scrollOffset = msg.scroll_offset;\n"
"    scrollCount = msg.scroll_count || 0;\n"
"  }\n"
"  if (scrollOffset > 0) {\n"
"    statusScroll.innerHTML = ' | <span class=\"scroll-info\">[' + scrollOffset + '/' + scrollCount + ']</span>';\n"
"  } else {\n"
"    statusScroll.textContent = '';\n"
"  }\n"
"}\n"
"\n"
"/* --- Mouse wheel scrollback --- */\n"
"termEl.addEventListener('wheel', function(e) {\n"
"  e.preventDefault();\n"
"  if (!ws || ws.readyState !== WebSocket.OPEN) return;\n"
"  /* deltaY < 0 = scroll up (into history), > 0 = scroll down (towards live) */\n"
"  var lines = 3; /* matches scrollback mouse_scroll_lines default */\n"
"  var delta = (e.deltaY < 0) ? lines : -lines;\n"
"  ws.send(JSON.stringify({type: 'scroll', delta: delta}));\n"
"}, {passive: false});\n"
"\n"
"/* --- Input handling (read-write mode) --- */\n"
"var keyMap = {\n"
"  'Enter': 'Enter', 'Backspace': 'Backspace', 'Tab': 'Tab',\n"
"  'Escape': 'Escape', 'ArrowUp': 'Up', 'ArrowDown': 'Down',\n"
"  'ArrowLeft': 'Left', 'ArrowRight': 'Right',\n"
"  'Home': 'Home', 'End': 'End',\n"
"  'PageUp': 'PageUp', 'PageDown': 'PageDown',\n"
"  'Insert': 'Insert', 'Delete': 'Delete',\n"
"  ' ': 'Space'\n"
"};\n"
"\n"
"document.addEventListener('keydown', function(e) {\n"
"  if (readOnly) return;\n"
"  if (!ws || ws.readyState !== WebSocket.OPEN) return;\n"
"  /* Don't capture if auth dialog is showing */\n"
"  if (authRequired) return;\n"
"\n"
"  var key = '';\n"
"\n"
"  if (e.ctrlKey && e.key.length === 1) {\n"
"    key = 'Ctrl+' + e.key.toLowerCase();\n"
"  } else if (keyMap[e.key]) {\n"
"    key = keyMap[e.key];\n"
"  } else if (e.key.length === 1) {\n"
"    /* Regular character - send as text, not as key name */\n"
"    ws.send(JSON.stringify({type: 'text', text: e.key}));\n"
"    e.preventDefault();\n"
"    return;\n"
"  } else {\n"
"    return; /* Unknown key, don't consume */\n"
"  }\n"
"\n"
"  e.preventDefault();\n"
"  ws.send(JSON.stringify({type: 'key', key: key}));\n"
"});\n"
"\n"
"/* --- Init --- */\n"
"updateModeDisplay();\n"
"checkAuthNeeded();\n"
"\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n"
;

#endif /* GST_WEBVIEW_HTML_H */
